// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fitwuhhukbayfijdbfsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpdHd1aGh1a2JheWZpamRiZnN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ5MDgxNDksImV4cCI6MjA2MDQ4NDE0OX0.aErDQCYPzjJGNVJvmKko4wMDP--HfSokhqUw1y36n28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);