name = "goon-guessr"
main = "counter.js"
compatibility_date = "2024-01-01"

kv_namespaces = [
  { binding = "GOON_GUESSR_KV", id = "${KV_NAMESPACE_ID}" }
]

[vars]
COUNTER_KEY = "counter"
LAST_RESET_KEY = "last_reset"